In [8]:
import math 

## 9. Sólo para practicar. Los números telefónicos en la ciudad de Cuernavaca, Morelos, constan de siete dígitos.

<font size="4"> **a)** ¿Cuántas líneas telefónicas pueden crearse en esa ciudad? Recuerda que no pueden comenzar con cero.</font>


Para calcular el número posible de líneas telefónicas en Cuernavaca, Morelos necesitamos considerar lo siguiente:

- Cada número telefónico consta de siete dígitos.
- El primer dígito no puede ser cero.
- Los seis dígitos restantes pueden ser cualquier número del 0 al 9.

Asi que para poder determinar el número total de líneas telefónicas que podemos crear, debemos analizar las posibilidades para cada dígito:

- Primer dígito: Tenemos 9 opciones (del 1 al 9).

- Dígitos restantes: Para cada uno de los seis dígitos restantes, tenemos 10 opciones (del 0 al 9).

Por lo tanto el número total de líneas telefónicas se calcula multiplicando el número de posibilidades para cada dígito:

$$Número\ de\ líneas\ telefónicas = 9 \times 10^6$$

Siguiendo esta lógica, se pueden crear un total de **9,000,000** líneas telefónicas. Implementando la lógica en python se ve de esta manera: 

In [4]:
primer_digito = 9 # Primer digito (1 al 9)
digitos_restantes = 10 # Digitos restantes (0 al 9)

lineas_telefonicas = primer_digito * math.pow(digitos_restantes, 6)

print("El número total de líneas telefónicas posibles es:", lineas_telefonicas)


El número total de líneas telefónicas posibles es: 9000000.0


<font size="4"> **b)** Si los tres primeros dígitos representan una zona de Cuernavaca, ¿cuántas líneas telefónicas pertenecen a la zona 326? </font>

Para calcular el número de líneas telefónicas en la zona 326, necesitamos considerar lo siguiente:

- Hay dígitos fijos: Los números telefónicos de la zona 326 de Cuernavaca comienzan con los dígitos 3, 2 y 6. Estos tres primeros dígitos no pueden variar.
- Hay dígitos variables: Los últimos cuatro dígitos pueden ser cualquier número del 0 al 9, lo que nos da 10 opciones para cada uno de ellos.

Para determinar cuántas líneas telefónicas pertenecen a la zona 326, calculamos las combinaciones posibles de los últimos cuatro dígitos:

$$Número\ de\ líneas = 10 * 10 * 10 * 10 = 10^4$$

Al realizar este cálculo, obtenemos:

$$Número\ de\ líneas = 10,000$$

Asi que en la zona 326 de Cuernavaca, se pueden crear un total de **10,000** líneas telefónicas. Al igual, implementemos esa logica en python:

In [5]:
digitos_variables = 10  # Opciones para cada uno de los últimos cuatro dígitos (0-9)

lineas_zona_326 = digitos_variables * math.pow(digitos_variables, 4)

print("b) El número de líneas telefónicas que se pueden crear en la zona 326 es:", lineas_zona_326)


b) El número de líneas telefónicas que se pueden crear en la zona 326 es: 100000.0


## 10. Sólo para practicar. Se tiene la palabra MURCIÉLAGO. Si no se permiten repeticiones al usar las letras que la forman, determina:


<font size="4"> **a)** El número de palabras que puedes crear.</font>

Imaginemos que tenemos 10 espacios en blanco para formar una palabra. 

En el primer espacio, podemos colocar cualquiera de las 10 letras disponibles. Para el segundo espacio, solo nos quedan 9 letras, ya que no puedes repetir la que ya usamos. En el tercer espacio, tendremos 8 opciones, y así sucesivamente.

Entonces se puede decir que el número total de palabras posibles se obtiene multiplicando el número de opciones para cada espacio:

$$10\ opciones \cdot 9\ opciones \cdot 8\ opciones \cdot ... \cdot 2\ opciones \cdot 1\ opción$$

A esta operación matemática se le conoce como factorial y se denota con el símbolo "!". En este caso, sería $10!$ (factorial de 10).

Asi obtenemos que el factorial de 10 es:

$$10! = 3,628,800$$

Siguiendo la misma lógica en python podemos crear el siguiente codigo:

In [7]:
n_letras = 10  # Número de letras distintas
total_palabras = math.factorial(n_letras)

print("El número total de palabras posibles es:", total_palabras)


El número total de palabras posibles es: 3628800


<font size="4"> **b)** El número de palabras con cinco letras.</font>

Siguiendo la misma lógica que en el anterior, podemos visualizar 5 espacios en blanco para formar palabras de cinco letras. 

En el primer espacio, tenemos 10 opciones de letras. En el segundo, nos quedan 9 opciones, y así hasta el quinto espacio.

El número total de palabras de cinco letras se calcula multiplicando el número de opciones para cada espacio:

$$10\ opciones \times 9\ opciones \times 8\ opciones \times 7\ opciones \times 6\ opciones = 30,240$$

Por lo tanto, podemos formar un total de 30,240 palabras diferentes de cinco letras utilizando 10 letras distintas sin repetirlas.

Para mejorar la lógica del un código que escribiremos en python para resolver este inciso, podemos utilizar una fórmula matemática.

La fórmula para calcular las permutaciones es:

$$ P(n,k) = \dfrac{n!}{(n-k)!}$$

En donde:
- 𝑛 es el número total de letras disponibles (10 en este caso) 
- 𝑘 es el número de letras en cada palabra (5 en este caso). 

Reemplazando los valores en nuestra formula quedaria de la siguiente manera: 

$$
\begin{align}
    _10P_5 &= \dfrac{10!}{(10 - 5)!}\\
    _10P_3 &= \dfrac{10!}{5!} = \dfrac{3,628,800}{120} \\
    _10P_3 &= 30,240
\end{align}
$$

Asi que esto se puede calcular de manera más eficiente usando la función math.perm en Python con el siguiente codigo:

In [8]:
n_letras = 10  # Número total de letras distintas
k_letras = 5   # Número de letras en cada palabra

# Calculamos el número de permutaciones de 10 letras tomando de 5 en 5
total_palabras = math.perm(n_letras, k_letras)

print("El número total de palabras de cinco letras es:", total_palabras)


El número total de palabras de cinco letras es: 30240


<font size="4"> **c)** La probabilidad de que una palabra de cinco letras termine en vocal.</font>

Para calcular la probabilidad de que una palabra de cinco letras termine en vocal tenemos que considerar que tenemos 5 vocales (A, E, I, O, U) en la palabra MURCIELAGO y tambien tenermos 5 consonantes en la palabra MURCIÉLAGO: M, R, C, L, G.

En el apartado anterior, calculamos que hay 30,240 palabras posibles de cinco letras con estas 10 letras distintas.

Para calcular la probabilidad tenemos que tener 2 cosas:

    1. Casos favorables
    2. Casos totales 

1. Los casos favorables:

- Para que una palabra termine en vocal, tenemos 5 opciones para la última letra.
- Las cuatro letras restantes se pueden elegir y ordenar de $P(9,4)$ maneras, que son las permutaciones de 9 elementos tomando de 4 en 4.

2. Casos totales:

- El número total de palabras de cinco letras es $P(10,5)$, que son las permutaciones de 10 elementos tomando de 5 en 5.




Sustituyendo los valores en la formula quedaria de la siguiente forma:

Para sacar el numero de letras se agarra una vocal para terminar, eso quiere decir que permutaremos las 4 letras de las 9 restantes, ya que hemos tomado una para el final.
$$
       {9}C{4}  = \dfrac{9!}{(9 - 4)!} = \dfrac{9!}{5!}\\
$$
Sabemos que el factrial de 5 es 120, pero falta el factorial de 9:

$$
    9! = 9 \cdot 8 \cdot 7 \cdot 6 \cdot 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 = 362880
$$
Asi que:
$$
    {9}C{4}  = \dfrac{62880}{120} = 3024\\
$$
Multiplicamos el resultado con las 5 maneras:

$$
    5 \times 3024 = 15120
$$

La probabilidad de que una palabra termine en vocal se calcula como:
$$Probabilidad = \frac{Casos\ favorables}{Casos\ totales}$$

La probabilidad de que una palabra de cinco letras termine en una vocal es el número de palabras que terminan en una vocal dividido por el número total de palabras de cinco letras, o sea:
$$
    Probabilidad = \dfrac {15120}{30240} = \dfrac {1}{2} = 0.5
$$

Por lo tanto, la probabilidad de que una palabra de cinco letras termine en vocal es un 0.5

Ahora implementemos la logica en python, quedaria de la siguiente manera:

In [10]:
n_vocales = 5 # Número de vocales disponibles

total_letras = 10 # Número total de letras disponibles

letras_por_palabra = 5 # Número de letras en cada palabra

letras_restantes = total_letras - 1 # Número de letras restantes después de seleccionar una vocal para la última posición

# Permutaciones de 9 letras tomadas de 4 en 4 (para las 4 letras restantes después de elegir la vocal)
casos_favorables = n_vocales * math.perm(letras_restantes, letras_por_palabra - 1)

# Permutaciones de 10 letras tomadas de 5 en 5 (total de palabras de 5 letras)
casos_totales = math.perm(total_letras, letras_por_palabra)

# Cálculo de la probabilidad
probabilidad = casos_favorables / casos_totales

print("La probabilidad de que una palabra de cinco letras termine en vocal es:", probabilidad*100,"%") 


La probabilidad de que una palabra de cinco letras termine en vocal es: 50.0 %


## 11 Parque vehicular. La Ciudad de México tiene placas de automóviles con tres números seguidos por tres letras, es decir, son placas del tipo 999-AAA. Sin embargo, no pueden empezar con 0 (cero) ni se utilizan las letras I, O, Q y Ñ.

#### a) ¿Cuántas placas diferentes son posibles?

Para calcular el número de placas diferentes posibles, debemos tener en cuenta las siguientes restricciones:
- Las placas tienen 3 números seguidos de 3 letras
- No pueden empezar con 0 (cero)
- No se utilizan las letras I, O, Q y Ñ

Se realizo el apartado donde las placas tienen tres numeros seguidos de tres letras el cual consta con 9 dijitos el primer espacio ya que el enunciado dice que en el primer espacio (digito) no acepta el 0.
- En el estacio dos y tres ya acepta todos los dijitos mencionados, desde el **0** hasta el **9** y eso hace referente al 10 porque del **0** al **9** existen 10 numeros.
- Y pasamos a realizar la multiplicacion para tener los posibles numeros diferentes.
$$
\begin{align}
    Números: & \quad 9 \times 10 \times 10 = 900 \\
\end{align}
$$

Pasamos a realizar con el de letras, solo que aqui no incluimos las letras indicadas entonces como el abecedario tiene **27** letras, a esos **27** le quitamos esas **4** letras y por eso mismo nos da **23** para poder realizar nuestras operaciones en los tres lugares donde vamos a pocisionar las letras.
$$
\begin{align}
    Letras:& \quad 23 \times 23 \times 23 = 12,167 \\
\end{align}
$$

Por ultimo para tener todas la posiblidades generales multiplicamos el resultado de numeros por el de letras y obtenemos **10,950,300** posibles placas.
$$
\begin{align}
    Placas diferentes:& \quad 900 \times 12,167 = 10,950,300
\end{align}
$$


In [1]:
pri_dig = 9 
otros_dig = 10  

numero_digitos = pri_dig * otros_dig * otros_dig
num_letras=23
num_posib_letras = num_letras ** 3

placas_totales = numero_digitos * num_posib_letras

print("a) Placas diferentes posibles:", placas_totales)

a) Placas diferentes posibles: 10950300


#### b) ¿Cuántas placas diferentes terminan en vocal?

Para este inciso solo es posible utilizar para las placas, las siguientes vocales como ultimo digito que son **A, E y U** porque el enunciado dice que no puedes usar 4 letras y en esas 4 se uncuentran dos vocales que son **I, O**.
- Entonces vamos a multiplicar las letras de la siguiente manera. Porque a diferencia del inciso anterior, en lugar del ultimo 23 que generaliza todas las letras ahi solo se pondran el numero de vocales que estan permitidas por el enunciado.
$$
\begin{align}
    Letras: & \quad 23 \times 23 \times 3 = 1,587 \\
\end{align}
$$
Nos da un resultado de **1587** diferentes terminaciones en vocal.
- Por ultimo esos **1587** se multiplicaran por los diferentes numeros, esa cantidad la podemos tomar del inciso anterior, y quedaria de la siguiente manera la multiplicacion.
$$
\begin{align}
    Placas diferentes en terminacion de vocal: & \quad 900 \times 1,587 = 1,428,300
\end{align}
$$

In [2]:
num_vocales = 3  
pterminan_vocal = numero_digitos * (num_letras * num_letras * num_vocales)

print("b) Placas que terminan en vocal:", pterminan_vocal)

b) Placas que terminan en vocal: 1428300


#### c) ¿Cuál es la probabilidad de que una placa, elegida al azar, sea impar?

- Probabilidad de que la placa termine en número impar:


- Primero se multiplico de esta manera porque 9 son los numeros que acepta el primer digito, el 10 porque son los numeros que acepta el segundo digito y 5 porque son la cantidad de numero impares que hay en ese rango de 0 a 9.
$$
\begin{align}
     & 9 \times 10 \times 5 = 450
\end{align}
$$

- Despues se multiplico de esta otra manera, 9 son los numeros que acepta el primer digito, el 10 porque son los numeros que acepta el segundo digito y el 10 porque son los numeros que acepta el tercer digito, ya que en el tercer digito deben ser todos los posbles numeros porque despues vamos a dividir para sacar la probabilidad.
$$
\begin{align}
     & 9 \times 10 \times 10 = 900
\end{align}
$$

- Por ultimo sacamos la probabilidad donde dividimos **450** que fue con numeros impares, entre **900** que fueron los numeros completos que esto representa un 100% de los posibles numeros.
$$
\begin{align}
     \text{Probabilidad de que la placa termine en número impar} = \frac{450}{900} = 0.5
\end{align}
$$

In [3]:
num_digitos_impares = 5
placas_impares = (pri_dig * otros_dig) * num_digitos_impares * num_posib_letras

probabilidad_impar = placas_impares / placas_totales

print("c) Probabilidad de que una placa, elegida al azar, sea impar:", probabilidad_impar)

c) Probabilidad de que una placa, elegida al azar, sea impar: 0.5


## 12 Servicios restauranteros. Una cadena de hamburguesas anuncia que se ofrecen 512 maneras de pedir una hamburguesa. Un cliente puede elegir cualquiera de estos ingredientes: cátsup, mostaza, mayonesa, aderezo de la casa, cebolla, pepinillos, jitomate, tocino y lechuga. ¿Crees que lo que afirma la empresa sea cierto? Justifica tu respuesta.

- Se conoce que tenemos 9 ingredientes en total los cuales los vamos a representar como **"n = 9"**.
- De los 9 ingredientes podemos escoger cuales quiera de esos 9 ingredientes donde lo vamos a representar como **"r"** , la cual puede ser de 0 a 9.
$$
\begin{align}
    _nC_r &= \dfrac{n!}{r!(n - r)!}\\ 
\end{align}
$$
- Para su resolucion se aplicara sumatoria de combinaciones:
$$
\begin{align}
    _\Sigma (_9C_r)\\
\end{align}
$$

- Se realizo los calculos de las conbinaciones, donde **"r"** va desde **0** hasta **9**. 
$$
\begin{align}
    _9C_0 &= \dfrac{9!}{0!(9 - 0)!} = 1\\
    _9C_1 &= \dfrac{9!}{1!(9 - 1)!} = 9\\
    _9C_2 &= \dfrac{9!}{2!(9 - 2)!} = 36\\
    _9C_3 &= \dfrac{9!}{3!(9 - 3)!} = 84\\
    _9C_4 &= \dfrac{9!}{4!(9 - 4)!} = 126\\
    _9C_5 &= \dfrac{9!}{5!(9 - 5)!} = 126\\
    _9C_6 &= \dfrac{9!}{6!(9 - 6)!} = 84\\
    _9C_7 &= \dfrac{9!}{7!(9 - 7)!} = 36\\
    _9C_8 &= \dfrac{9!}{8!(9 - 8)!} = 9\\
    _9C_9 &= \dfrac{9!}{9!(9 - 9)!} = 1\\
\end{align}
$$

- Una vez teniendo todas las combinaciones hacemos la sumatoria de ellas para saber el total en general.
$$
\begin{align}
    Combinaciones &= 1 + 9 + 36 + 84 + 126 + 126 + 84 + 36 + 9 + 1 = 512
\end{align}
$$


Entonces concluimos que se pueden realizar **512** combinaciones de hamburguesas.

In [ ]:
from math import factorial

def combinaciones(n, r):
    return factorial(n) // (factorial(r) * factorial(n-r))

compar = 0
for r in range(10):
    compar += combinaciones(9, r)
print(f"Existen {int(compar)} combinaciones de hamburguesas")


## 13 
Una persona tiene un libro de cada uno de los autores siguientes: Mario Vargas Llosa,
Alberto Ruy Sánchez, Gabriel García Márquez, Günther Grass, Patrick Süskind, Heinrich Böll,
Arturo Pérez-Reverte y Camilo José Cela.

Como aún no los ha leído, quiere ponerlos en una
repisa cerca de su cama. De acuerdo con esto, determina:


- a) ¿De cuántas formas puede acomodar los libros sobre la repisa?


Debido a que no pide que se acomode de una manera en especifica, solamente necesitamos calcular el factorial del total de libros que tenemos

Solución:

$$
\begin{align}
8! = 8 \cdot 7 \cdot 6 \cdot 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 = 40{,}320
\end{align}
$$

Por lo cual existen **40,320 formas** de acomodar los libros 



In [ ]:
# Implementación de la solución del incisio a) del ejercicio 13
a = 8
formas_acomodar = math.factorial(a)

print(f'Hay {formas_acomodar} formas de acomodar los libros sobre la repisa')

- b) ¿De cuántas maneras puede ordenarlos si quiere que los libros de autores latinoamericanos estén juntos?


Antes de hacer los calculos correspondientes deberemos saber cuales autores son latinoamericanos

Latinoamericanos: Mario Vargas Llosa, Alberto Ruy Sánchez, Gabriel García Márquez

Conociendo que autores son Latinoamericanos los contemplaremos como un solo bloque, en lugar de tener 8 autores ahora tendremos 6 (Un bloque de autores Latinoamericanos y 5 de otros autores)

- Primero, vamos a calcular el número de formas de ordenar estos 6 elementos:
$$
\begin{align}
6! = 6 \cdot 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 = 720
\end{align}
$$

- Debemos considerar que los 3 libros dentro del bloque de Latinoamericanos se pueden ordenar de maneras diferentes, por lo cual calculamos las formas en que se pueden ordenar ese bloque de manera interna
$$
\begin{align}
3! = 3 \cdot 2 \cdot 1 = 6
\end{align}
$$

- Para obtener el número total de formas de ordenar los libros, multiplicamos las permutaciones de los 6 elementos por las permutaciones dentro del bloque latinoamericano:
$$
\begin{align}
6! \cdot 3! = 720 \cdot 6 = 4{,}320
\end{align}
$$

Entonces existe **4320 maneras** de ordenarlos si solo los autores latinoamericanos deben de estar juntos 


In [ ]:
# Implementación de la solución del incisio b) del ejercicio 13

resto_autores = 6
lat_autores = 3

# Maneras de ordenar 6 elementos
libros_6_ = math.factorial(resto_autores)

# Maneras de ordenar 3 libros dentro del bloque
libros_3_ = math.factorial(lat_autores)

# Número total de maneras
total = libros_6_ * libros_3_


print(f'Existen {total} maneras de ordenar los libros si los autores latinoamericanos deben de estar juntos')


- c) ¿De cuántas formas puede acomodarlos, si los autores latinoamericanos deben estar juntos, así como los autores alemanes y los españoles también?


Necesitamos saber cuales son los autores Alemanes y Españoles
Alemanes: Günther Grass, Patrick Süskind, Heinrich Böll
Españoles: Arturo Pérez-Reverte, Camilo José Cela

Una vez sabiendo esto los separaremos en 3 bloques 
Bloque 1: Autores Latinoamericanos (Mario Vargas Llosa, Alberto Ruy Sánchez, Gabriel García Márquez)
Bloque 2: Autores Alemanes (Günther Grass, Patrick Süskind, Heinrich Böll)
Bloque 3: Autores Españoles (Arturo Pérez-Reverte, Camilo José Cela)

- Primero, calculamos el número de formas de ordenar estos 3 bloques:
$$
\begin{align}
3! = 3 \cdot 2 \cdot 1 = 6
\end{align}
$$

- Ahora calculamos las formas de ordenar dentro de cada bloque 
$$
\begin{align}
Latinoamericanos: ~ 3! = 3 \cdot 2 \cdot 1 = 6 \\
Alemanes: ~ 3! = 3 \cdot 2 \cdot 1 = 6 \\
Españoles: ~ 2! = 2 \cdot 1 = 2 \\
\end{align}
$$

- Para obtener el número total de formas de ordenar los libros, multiplicamos las permutaciones de los 3 bloques por las permutaciones dentro de cada bloque:
$$
\begin{align}
3! \cdot 3! \cdot 3! \cdot 2!= 6 \cdot 6 \cdot 6 \cdot 2 = 432
\end{align}
$$

Entonces llegamos a la conclusión de que existen **432 maneras** de acomodar los libros si los autores latinoamericanos, alemanes y españoles deben estar juntos








In [ ]:
# Implementación de la solución del incisio b) del ejercicio 13

lat_autores = 3
al_autores = 3
es_autores = 2

# Número de maneras de ordenar 3 bloques (Los autores de dividen en 3 bloques)
permutaciones_b = math.factorial(3)

# Maneras de ordenar libros dentro de cada bloque
permutaciones_la = math.factorial(lat_autores)
permutaciones_al = math.factorial(al_autores)
permutaciones_es = math.factorial(es_autores)

# Número total de formas
total = (permutaciones_b * permutaciones_la * permutaciones_al * permutaciones_es)

print(f'Entonces existen {total} maneras de acomodar los libros si se desea que los autores latinoamericanos, alemanes y españoles esten juntos')

- d) Determina las probabilidades correspondientes a los incisos (b) y (c).

En el inciso (b), queremos encontrar la probabilidad de que los libros de autores latinoamericanos estén juntos.
- Número total de formas de acomodar los libros:
$$
\begin{align}
8! = 40{,}320
\end{align}
$$
- Número de formas de acomodar los libros con los autores latinoamericanos juntos:
$$
\begin{align}
4{,}320
\end{align}
$$
- Probabilidad
$$
\begin{align}
P(Latinoamericanos~juntos) &= \dfrac{4320}{40320} &= 0.107 
\end{align}
$$

Entonces la probabilidad de que los autores latinoamericanos estén juntos es de 0.107




En el inciso (c), queremos encontrar la probabilidad de que los autores latinoamericanos, alemanes y españoles estén juntos en sus respectivos grupos

- Número total de formas de acomodar los libros:
$$
\begin{align}
8! = 40{,}320
\end{align}
$$
- Número de formas de acomodar los libros con los autores latinoamericanos, alemanes y españoles juntos en sus respectivos grupos:
$$
\begin{align}
432
\end{align}
$$
- Probabilidad
$$
\begin{align}
P(Todos~los~grupos~juntos) &= \dfrac{432}{40320} &= 0.0107 
\end{align}
$$

Entonces la probabilidad de que los autores latinoamericanos, alemanes y españoles estén juntos es de 0.0107

In [ ]:
# Implementación de la solución del incisio b) del ejercicio 13

# Número total de maneras de ordenar 8 libros
total_m = 40320

# Probabilidad para el inciso (b)
probabilidad_b = 4320 / total_m

# Probabilidad para el inciso (c)
probabilidad_c = 432 / total_m

print("Probabilidad del inciso (b):", probabilidad_b)
print("Probabilidad del inciso (c):", probabilidad_c)

## 14 
Finanzas. Se va a formar un portafolio de inversión de cuatro instrumentos financieros a partir
de cinco de renta fija y seis de renta variable. ¿De cuántas maneras podría formarse el portafolio
si:

- a) No hay restricciones?


Debido a que no hay restricciones en la selección de los instrumentos financieros, tenemos que elegir 4 instrumentos de los 11 disponibles (5 de renta fija y 6 de renta variable).
Utilizaremos la formula de combinaciones
$$
_nC_r = \dfrac{n!}{r!(n - r )!}
$$

Calculamos las combinaciones de 4 instrumentos de los 11 posibles
$$
\begin {align}
    _11C_4 = \dfrac{11!}{4!(11 - 4 )!}\\
    _11C_4 = \dfrac{11!}{4!(7)!}\\
    _11C_4 = \dfrac{11 \cdot 10 \cdot 9 \cdot 8 \cdot 7!}{4!(7)!}\\
    _11C_4 = \dfrac{11 \cdot 10 \cdot 9 \cdot 8}{4 \cdot 3 \cdot 2 \cdot 1}\\
    _11C_4 = \dfrac{7920}{24}\\
    _11C_4 = 330    
\end{align}
$$
Entonces hay **330 maneras** de formar el portafolio sin restricciones.


In [ ]:
# Implementación de la solución del incisio a) del ejercicio 14

n, r = 11, 4

sin_restricciones = math.comb(n, r)

print(f'Existen {sin_restricciones} maneras de formar el portafolio sin restricciones')

- b) Debe haber dos instrumentos de renta fija y dos de renta variable?


Seguiremos utilizando combinaciones, por lo cual primero vamos a elegir 2 instrumentos de renta fija de los 5 que están disponibles

$$
\begin {align}
    _5C_2 = \dfrac{5!}{2!(5 - 2 )!}\\
    _5C_2 = \dfrac{5!}{2!(3)!}\\
    _5C_2 = \dfrac{5 \cdot 4 \cdot 3!}{2!(3)!}\\
    _5C_2 = \dfrac{5 \cdot 4}{2 \cdot 1 }\\
    _5C_2 = \dfrac{20}{2}\\
    _5C_2 = 10    
\end{align}
$$

Ahora vamos a elegir 2 instrumentos de renta variable de los 6 que estan disponibles 
$$
\begin {align}
    _6C_2 = \dfrac{6!}{2!(6 - 2 )!}\\
    _6C_2 = \dfrac{6!}{2!(4)!}\\
    _6C_2 = \dfrac{6 \cdot 5 \cdot 4!}{2!(4)!}\\
    _6C_2 = \dfrac{6 \cdot 5}{2 \cdot 1 }\\
    _6C_2 = \dfrac{30}{2}\\
    _6C_2 = 15    
\end{align}
$$
Por ultimo vamos a multiplicar las combinaciones 
$$
\begin {align}
_5C_2 ~ \cdot ~ _6C_2 = 10 \cdot 15 = 150
\end{align}
$$

Entonces sabemos que hay 150 maneras de formar el portafolio si se debe de tener dos instrumentos de renta fija y dos de renta variable

In [ ]:
# Implementación de la solución del incisio b) del ejercicio 14

# Definir los valores
renta_fija = 5
renta_variable = 6
portafolio = 4

# Calcular las combinaciones
combinaciones_renta_fija = math.comb(renta_fija, 2)
combinaciones_renta_variable = math.comb(renta_variable, 2)

# Multiplicar las combinaciones para obtener el total
num_total_combinaciones = combinaciones_renta_fija * combinaciones_renta_variable

print(f"El número de maneras de formar el portafolio con 2 instrumentos de renta fija y 2 de renta variable es: {num_total_combinaciones}")

- c) No debe haber ningún instrumento de renta fija?


Para calcular el número de maneras de formar el portafolio si no debe haber ningún instrumento de renta fija (es decir, todos los instrumentos deben ser de renta variable)

Debemos de elegir 4 instrumentos de renta variable de los 6 que estan disponibles
$$
\begin {align}
    _6C_4 = \dfrac{6!}{4!(6 - 4 )!}\\
    _6C_4 = \dfrac{6!}{4!(2)!}\\
    _6C_4 = \dfrac{6 \cdot 5 \cdot 4!}{4!(2)!}\\
    _6C_4 = \dfrac{6 \cdot 5}{2 \cdot 1 }\\
    _6C_4 = \dfrac{30}{2}\\
    _6C_4 = 15    
\end{align}
$$
Entonces existen 15 maneras de formar el portafolio sin ningún instrumento de renta fija

In [ ]:
# Implementación de la solución del incisio c) del ejercicio 14

# Definir los valores
renta_variable = 6
portafolio = 4

# Calcular las combinaciones
num_combinaciones = math.comb(renta_variable, portafolio)

print(f"El número de maneras de formar el portafolio sin ningún instrumento de renta fija es: {num_combinaciones}")


- d) Debe haber tres instrumentos de renta fija?


Primeramente deberemos de elegir 3 instrumentos de renta fija de los 5 que tenemos disponibles 

$$
\begin {align}
    _5C_3 = \dfrac{5!}{3!(5 - 3)!}\\
    _5C_3 = \dfrac{5!}{3!(2)!}\\
    _5C_3 = \dfrac{5 \cdot 4 \cdot 3!}{3!(2)!}\\
    _5C_3 = \dfrac{5 \cdot 4}{2 \cdot 1 }\\
    _5C_3 = \dfrac{20}{2}\\
    _5C_3 = 10    
\end{align}
$$

Ahora debemos de elegir 1 instrumento de renta variable de los 6 disponibles
$$
\begin {align}
    _6C_1 = \dfrac{6!}{1!(6 - 1)!}\\
    _6C_1 = \dfrac{6!}{1!(5)!}\\
    _6C_1 = \dfrac{6 \cdot 5!}{1!(5)!}\\
    _6C_1 = \dfrac{6}{1}\\
    _6C_1 = 6    
\end{align}
$$

Por ultimo tenemos que multiplicar ambas combinaciones
$$
\begin{align}
_5C_3 ~ \cdot ~ _6C_1 = 10 \cdot 6 = 60
\end{align}
$$

Entonces tenemos como resultado que hay 60 maneras de formar el portafolio si debe de haber 3 instrumentos de renta fija

In [ ]:
# Implementación de la solución del incisio d) del ejercicio 14

# Calcular las combinaciones
combinaciones_renta_fija = math.comb(renta_fija, 3)
combinaciones_renta_variable = math.comb(renta_variable, 1)

# Multiplicar las combinaciones para obtener el total
total_combinaciones = combinaciones_renta_fija * combinaciones_renta_variable

print(f"El número de maneras de formar el portafolio con exactamente 3 instrumentos de renta fija y 1 de renta variable es: {total_combinaciones}")


- e) Calcula las probabilidades para los incisos anteriores.


La probabilidad del inciso a) es 1 debido a que se consideran todas las combinaciones posibles 

$$
\begin{align}
P(Sin~restricciones) = \dfrac{330}{330} = 1
\end{align}
$$

Probabilidad inciso b) (Dos renta fija y dos de renta variable)

Sabemos que hay 150 maneras de formar el portafolio con esa condición, entonces:  
$$
\begin{align}
P(2~renta~fija~y~2~renta~variable) = \dfrac{150}{330} = 0.4545  
\end{align}
$$

Probabilidad inciso c) (Ningún instrumento de renta fija)
Sabemos que hay 15 maneras de formar el portafolio con dicha condición, entonces: 
$$
\begin{align}
P(0~renta~fija) = \dfrac{15}{330} = 0.0455
\end{align}
$$

Probabilidad inciso d) (3 instrumentos de renta fija)
Sabemos que hay 60 maneras de formar el portafolio con esa condición, entonces:
$$
\begin{align}
P(3~renta~fija) = \dfrac{60}{330} = 0.1818
\end{align}
$$


In [ ]:
# Probabilidades para los diferentes incisos
prob_a = 1.0  # Probabilidad para inciso a) sin restricciones es siempre 1.0

# Número de combinaciones calculadas previamente
num_comb_b = 150
num_comb_c = 15
num_comb_d = 60

# Número total de combinaciones sin restricciones
total_combinations = 330

# Calcular probabilidades para los incisos b), c) y d)
prob_b = num_comb_b / total_combinations
prob_c = num_comb_c / total_combinations
prob_d = num_comb_d / total_combinations

print(f"Probabilidad para el inciso b): {prob_b:.4f}")
print(f"Probabilidad para el inciso c): {prob_c:.4f}")
print(f"Probabilidad para el inciso d): {prob_d:.4f}")


f) Investiga qué es un instrumento de renta fija y otro de renta variable.

Renta fija: Los instrumentos de renta fija son activos financieros que representan un préstamo que un inversionista hace a un emisor (generalmente un gobierno, una empresa o una entidad financiera) a cambio de recibir pagos de interés regulares y el reembolso del capital al vencimiento del instrumento.

Renta Variable: son activos financieros cuyo valor puede fluctuar en el mercado, lo que significa que no hay certeza sobre el rendimiento de la inversión y el inversor asume un mayor riesgo en comparación con los instrumentos de renta fija.

## 15 Futbol. Tres parejas (tres hombres y tres mujeres) compran boletos para ir a un partido de los Pumas. Cuando llegan al estadio de Ciudad Universitaria les surge la duda de cómo sentarse en la fila. ¿De cuántas maneras pueden hacerlo si:

- a) No hay restricciones?

En este caso solo queremos saber de cuantas maneras se pueden sentar si son 6 personas, entonces usamos el 6 factorial 
$$
\begin{align}
      6! &= 6×5×4×3×2×1=720
\end{align}      
$$      
Entonces se pueden sentar de 720 maneras 

In [1]:
from math import factorial
n = 6
total_maneiras = factorial(n)
total_maneiras

720

- b) Los hombres deben sentarse juntos?

En este inciso se forman 4 bloques ya que hay 3 hombres que deben sentarse juntos y forman un bloque, los otros 3 espacios cada uno cuenta como un bloque, entonces primero calculamos el numero de formas en la que se puede ordenar los 4 bloques usando factorial
$$
\begin{align}
      4! &= 4×3×2×1=24
\end{align}      
$$ 
Ahora calculamos las formas en la que el bloque de hombres pueden sentarse ya que hay 3 hombres, usamos el factorial de 3
$$
\begin{align}
      3! &= 3×2×1=6
\end{align}      
$$ 
Y por ultimo multiplicamos el numero de formas que obtubimos de cada factorial para obtener el numero de total de maneras en que los hombres pueden sentarse juntos
$$
\begin{align}
      4!×3! &=24×6=144
\end{align}      
$$ 

In [2]:
from math import factorial

# Número de bloques
n_bloques, n_hombres = 4, 3

factorial_bloques = factorial(n_bloques)
factorial_hombres = factorial(n_hombres)
total_maneiras_hombres_juntos = factorial_bloques * factorial_hombres

print("El total de maneras en la que pueden sentarse los hombres juntos es: ", total_maneiras_hombres_juntos)

El total de maneras en la que pueden sentarse los hombres juntos es:  144


- c) Deben sentarse por parejas?

En este caso se forman 3 bloques ya que hay 3 hombres y 3 mujeres, entonces usamos el factorial de 3 para saber de cuantas formas se pueden sentar
$$
\begin{align}
      3! &= 3×2×1=6
\end{align}      
$$
Pero en cada bloque hay un hombre y una mujer, entonces usamos en factorial de 2 para saber de cuantas formas se pueden sentar y lo multiplicamos por 3 porque hay 3 bloques
$$
\begin{align}
      (2!)^3&=2×2×2=8
\end{align}      
$$
Ahora multimplicamos los resultados obtenidos
$$
\begin{align}
      3!×(2!)^3=6×8=48
\end{align}      
$$
Hay 48 maneras en que las parejas pueden sentarse juntas

In [3]:
from math import factorial

n_bloques, n_personas_por_bloque = 3, 2

factorial_bloques = factorial(n_bloques)
factorial_personas_por_bloque = factorial(n_personas_por_bloque) ** n_bloques
total_maneiras_por_parejas = factorial_bloques * factorial_personas_por_bloque

print(f"Hay {total_maneiras_por_parejas} maneras en que las parejas pueden sentarse juntas")

Hay 48 maneras en que las parejas pueden sentarse juntas


- d) ¿Cuál es la probabilidad de cada uno de los eventos descritos en los incisos anteriores?

Para el inciso b usamos la siguiente formula:
$$
\begin{align}
      P(Hombres-juntos) &= \dfrac{Numero-de-maneras-con-hombres-juntos}{Numero-total-de-maneras} = \dfrac{144}{720} =\dfrac{1}{5} =0.2 \\\
\end{align}      
$$
Para el inciso c usamos la siguiente formula:
$$
\begin{align}
      P(Por-parejas) &= \dfrac{Numero-de-maneras-por-parejas}{Numero-total-de-maneras} = \dfrac{48}{720} =\dfrac{1}{15} =0.0667 \\\
\end{align}      
$$

In [5]:
from math import factorial

total_maneiras = factorial(6)

total_maneiras_hombres_juntos = factorial(4) * factorial(3)
prob_hombres_juntos = total_maneiras_hombres_juntos / total_maneiras

total_maneiras_por_parejas = factorial(3) * (factorial(2) ** 3)
prob_por_parejas = total_maneiras_por_parejas / total_maneiras

print("Probabilidad del inciso b: ",prob_hombres_juntos)
print("Probabilidad edl inciso c: ", prob_por_parejas)

Probabilidad del inciso b:  0.2
Probabilidad edl inciso c:  0.06666666666666667


## 16 Trabajo en equipo. En un grupo de 25 alumnos hay 13 chicas y 12 chicos. Se desean formar equipos de trabajo para realizar una investigación:

- a) ¿Cuántos equipos de cinco personas pueden formarse?

Para este caso ocuamos la formula de combinaciones para no repetir integrantes:
$$ \begin{align} 
_nC_r &= \dfrac{n!}{(n - r)!r!}\\ 
_25C_5 &= \dfrac{25!}{(25 - 5)!5!}\\ 
_25C_5 &= \dfrac{25!}{20!x5!} = \dfrac{25×24×23×22×21
​}{5×4×3×2×1}\\ 
_25C_5 &= 53,130 
\end{align} 
$$

In [9]:
n, k = 25, 5  
equipos = math.comb(n, k)

print(f"El número de equipos de {k} personas que se pueden formar es: {equipos}")

El número de equipos de 5 personas que se pueden formar es: 53130


- b) ¿Cuántos equipos pueden formarse si debe haber una chica?

Para este caso ya calculamos el numero de equipos que formamos sin restricciones, la cantidad es 53130
y ahora hay que calcular el numero de equipos en donde no hay ninguna chica usando la formula de combinaciones:
$$ \begin{align} 
_nC_r &= \dfrac{n!}{(n - r)!r!}\\ 
_12C_5 &= \dfrac{12!}{(12 - 5)!5!}\\ 
_12C_5 &= \dfrac{12!}{7!x5!} = \dfrac{12×11×10×9×8}{5×4×3×2×1}\\ 
_12C_5 &= 792 
\end{align} 
$$
Ahora restamos la primera cantidad menos la segunda 
$$ 
\begin{align} 
53130−792&=52,338 
\end{align} 
$$
Entonces hay 52338 formas en donde hay una niña en el equipo

In [10]:
from scipy.special import comb

total_alumnos = 25
num_chicas = 13
num_chicos = 12
num_por_equipo = 5 

total_combinaciones = comb(total_alumnos, num_por_equipo, exact=True)
combinaciones_sin_chicas = comb(num_chicos, num_por_equipo, exact=True)
combinaciones_con_chicas = total_combinaciones - combinaciones_sin_chicas

print(f"Combinaciones con al menos una chica: {combinaciones_con_chicas}")

Combinaciones con al menos una chica: 52338


- c) ¿Cuántos equipos pueden formarse si debe haber dos chicas?

Para este caso elegimos 2 chicas de las 13 que hay y elegimos 3 chicos de los 12 que hay y usamos combinacion: 
$$ 
\begin{align} 
_nC_r &= \dfrac{n!}{(n - r)!r!}\\ 
_13C_2 &= \dfrac{13!}{(13 - 2)!2!}\\ 
_13C_2 &= \dfrac{13!}{11!x2!} = \dfrac{6,227,020,800}{79,833,600}\\ 
_13C_2 &= 78 
\end{align} 
$$
Ahora para el de chicos:
$$ 
\begin{align} 
_nC_r &= \dfrac{n!}{(n - r)!r!}\\ 
_12C_3 &= \dfrac{12!}{(12 - 3)!3!}\\ 
_12C_3 &= \dfrac{12!}{9!x3!} = \dfrac{479,001,600}{2,177,280}\\ 
_12C_3 &= 220 
\end{align} 
$$
Por ultimo multiplicamos los resultados
$$ 
\begin{align}
78×220&=17,160 
\end{align} 
$$
Hay 17,160 formas donde dos personas son chicas

In [11]:
from math import comb

num_chicas = 13
num_chicos = 12
num_por_equipo = 5  
equipos_con_dos_chicas = comb(num_chicas, 2) * comb(num_chicos, num_por_equipo - 2)

print(f"El número de equipos con exactamente dos chicas es: {equipos_con_dos_chicas}")

El número de equipos con exactamente dos chicas es: 17160


- d) Determina las probabilidades correspondientes a los incisos anteriores.

Para calcular la probabilidad del inciso b usamos la siguiente formula:
$$
\begin{align}
      P(Al-menos-una-chica) &= \dfrac{Numero-de-equipos-con-una-chica}{Numero-total-de-equipos} = \dfrac{52,338}{53,130} =0.985 \\\
\end{align}      
$$
Para calcular la probabilidad del inciso c usamos la siguiente formula:
$$
\begin{align}
      P(Al-menos-dos-chica) &= \dfrac{Numero-de-equipos-con-exactamente-dos-chicas}{Numero-total-de-equipos} = \dfrac{17,160}{53,130} =0.323\\\
\end{align}      
$$

In [13]:

equipos_totales = comb(25, 5)
equipos_con_al_menos_una_chica = 52338
equipos_con_exactamente_dos_chicas = comb(13, 2) * comb(12, 3)

prob_al_menos_una_chica = equipos_con_al_menos_una_chica / equipos_totales
prob_exactamente_dos_chicas = equipos_con_exactamente_dos_chicas / equipos_totales

print(f"Probabilidad de que haya al menos una chica: {prob_al_menos_una_chica:.4f}")
print(f"Probabilidad de que haya exactamente dos chicas: {prob_exactamente_dos_chicas:.4f}")

Probabilidad de que haya al menos una chica: 0.9851
Probabilidad de que haya exactamente dos chicas: 0.3230


## 17 Control de calidad. Se tiene una caja con 24 latas y se sabe que dos están contaminadas. Se van a seleccionar tres latas al azar para someterlas a una prueba de control de calidad, es decir, para medir los estándares de calidad de la empresa.

- a) ¿Cuántas combinaciones de tres latas pueden hacerse?

Para este primer inciso usamos la formula de combinacion
$$ 
\begin{align} 
_nC_r &= \dfrac{n!}{(n - r)!r!}\\ 
_24C_3 &= \dfrac{24!}{(24 - 3)!3!}\\ 
_24C_3 &= \dfrac{24!}{21!x3!} = \dfrac{24×23×22×21}{21! x 6}\\ 
_24C_3 &= \dfrac{12144}{6}\\
_24C_3 &= 2024
\end{align} 
$$
Pueden hacerse 2,024 combinaciones de latas

In [15]:
factorial_24 = math.factorial(24)
factorial_21 = math.factorial(21)
factorial_3 = math.factorial(3)

resultado = factorial_24 // (factorial_21 * factorial_3)

print(f"Se puedenn hacer {resultado} combinaciones de latas")

Se puedenn hacer 2024 combinaciones de latas


- b) ¿Cuál es la probabilidad de que se seleccione una lata contaminada para la prueba?

Para calcular la probabilidad usamos la siguiente formula:
$$
\begin{align}
      P(contaminada) &= \dfrac{Numero-de-latas-contaminadas}{Numero-total-de-posibles-selecciones} = \dfrac{2}{2024} \\\
\end{align}      
$$

In [16]:
from math import comb

total_latas = 24
latas_contaminadas = 2
latas_no_contaminadas = total_latas - latas_contaminadas
latas_seleccionadas = 3

total_combinaciones = comb(total_latas, latas_seleccionadas)
combinaciones_con_contaminadas = comb(latas_contaminadas, 1) * comb(latas_no_contaminadas, latas_seleccionadas - 1)
probabilidad_contaminada = combinaciones_con_contaminadas / total_combinaciones

probabilidad_contaminada 

0.22826086956521738

- c) ¿Cuál es la probabilidad de que se seleccione al menos una lata contaminada para la prueba?

Para este inciso usaremos 3 formulas:
$$
\begin{align}
      P(no-contaminada) &= \dfrac{22}{24} = \dfrac{11}{12} \\\
\end{align}      
$$
$$
\begin{align}
      P(ninguna-contaminada-en-3-intentos) &= (\dfrac{11}{12})^3 = \dfrac{1331}{1728}\\\
\end{align}      
$$
La probabilidad es:
$$
\begin{align}
      P(al-menos-una-lata-contaminada) &= 1 - \dfrac{1331}{1728} = \dfrac{397}{1728}\\\
\end{align}      
$$


In [17]:
from fractions import Fraction

total_latas = 24
latas_contaminadas = 2
latas_seleccionadas = 3

probabilidad_no_contaminada = Fraction((total_latas - latas_contaminadas), total_latas)
probabilidad_ninguna_contaminada = probabilidad_no_contaminada ** latas_seleccionadas
probabilidad_al_menos_una_contaminada = 1 - probabilidad_ninguna_contaminada

print("La probabilidad de seleccionar al menos una lata contaminada es:", probabilidad_al_menos_una_contaminada)

La probabilidad de seleccionar al menos una lata contaminada es: 397/1728


- d) ¿Y la probabilidad de que no se elijan latas contaminadas para la prueba?

En este caso solo usaremos una formula:
$$
\begin{align}
      P(ninguna-contaminada) &= 1-\dfrac{397}{1728}   \\\
\end{align}      
$$

In [18]:
from fractions import Fraction

probabilidad_al_menos_una_contaminada = Fraction(397, 1728)
probabilidad_ninguna_contaminada = 1 - probabilidad_al_menos_una_contaminada

print("La probabilidad de no seleccionar latas contaminadas es:", probabilidad_ninguna_contaminada)

La probabilidad de no seleccionar latas contaminadas es: 1331/1728
